import { Metadata } from "next";
import Image from "next/image";
import  AguaPrincipal  from "@/img/agua1.jpeg"
import  AguaDois  from "@/img/agua2.jpeg"
import  AguaTres  from "@/img/agua3.jpeg"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {

  const style = {
    cards: " flex flex-wrap justify-evenly mt-12 ",
    card: " w-96 mb-10 hover:scale-110 ",
    cardImage: " h-60 rounded-t-3xl ",
    colorTitle: " text-sm font-bold mt-2 ",
    cardTexts: " flex flex-col items-center ",
    h2: " text-[34px] font-bold ",
    cardTextPrin: " p-4 text-center text-stone-400 ",
    obs: " grid grid-flow-col justify-stretch rounded-b-3xl text-white ",
    miniObs: " border-2 text-center py-1.5 ",
    miniTextPrin: " text-[20px] font-bold ",
  }


  // Tem que terminar
  const dados: {imagem: string, corTitle: string, contTitle: string, conth2: string, contTextPrin: string, obsColor: string, borderMiniObs: string} [] = [
    // {
    //   imagem: "AguaPrincipal",
    //   corTitle: "text-pink-600",
    // }
  ]

  return (
    <>

    {dados.map((item, index) => (
      <div key={index} className={style.cards}>
        <div className={style.card}>
          <Image src={item.imagem} className={style.cardImage} alt="" />
          <div className={style.cardTexts}>
            <p className={style.colorTitle + item.corTitle}>4 days ago</p>
            <h2 className={style.h2}>Post One</h2>
            <p className={style.cardTextPrin}>Acredita-se que no início do século 16 (dezesseis), uma gráfica imprimiu uma página de teste utilizando partes aleatórias de outros documentos dando origem ao Lorem Ipsum.</p>
          </div>
          <div className={style.obs + "bg-pink-600"}>
            <div className={style.miniObs + "border-pink-700 rounded-bl-3xl"}>
              <p className={style.miniTextPrin}>texto</p>
              <p>texto</p>
            </div>
            <div className={style.miniObs + "border-pink-700"}>
              <p className={style.miniTextPrin}>texto</p>
              <p>texto</p>
            </div>
            <div className={style.miniObs + "border-pink-700 rounded-br-3xl"}>
              <p className={style.miniTextPrin}>texto</p>
              <p>texto</p>
            </div>
          </div>
        </div>
      </div>
    ))}

    </>
  );
}
